language: python

python:
  - 3.4
  - 3.5
  - 3.6

sudo: required
matrix:
  include:
    - arch: arm64
      python: 3.6
      env: PIP_NO_CACHE_DIR=off 
    
install:
  - pip install cryptography

script:
  - python setup.py install
  - cd test
  - sudo ./run_tests
